# Generated by Django 4.1.3 on 2022-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0002_alter_gry_options_remove_gry_gatunek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
    ]
