# Generated by Django 4.1.3 on 2022-12-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0003_producent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gry',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gry.producent'),
        ),
    ]
