# Generated by Django 4.1.3 on 2023-01-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0006_rename_gatunek_gry_gatunek'),
    ]

    operations = [
        migrations.AddField(
            model_name='gry',
            name='zdjecie',
            field=models.ImageField(default='images/image0.jpg', upload_to='images'),
        ),
    ]
