# Generated by Django 4.1.3 on 2023-01-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0007_gry_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gry',
            name='zdjecie',
            field=models.ImageField(default='Sklep/Gry/static/image0.jpg', upload_to='Sklep/Gry/static'),
        ),
    ]
