# Generated by Django 4.1.3 on 2023-01-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0012_userwishgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gry',
            name='zdjecie',
            field=models.ImageField(default='static/temp.jpg', upload_to=''),
        ),
    ]
