# Generated by Django 4.1.3 on 2023-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0015_alter_gry_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gry',
            name='zdjecie',
            field=models.ImageField(default='static/image0.png', upload_to=''),
        ),
    ]
